[workspace]
resolver = "2"
members = [
    "contracts/provider-registry",
    "contracts/care-agreement",
]

[workspace.package]
edition = "2021"
rust-version = "1.91.0"

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true

[profile.dev]
overflow-checks = true
